# Generated by Django 3.1.1 on 2020-10-22 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    intital = True

    depencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.AutoField(auto_created=True,primary_key=True, serialize=False, verbose_name='id')),
                ('poll_id', models.IntegerField()),
                ('title', models.CharField(max_length=200)),
                ('count', models.IntegerField(default=0)),
            ],
    
    ),
    Migrations.CreateMode(
        name='Poll', 
        fields=[
            ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ('subject',models.CharField(max_length=200)),
            ('description',models.TextField()),
            ('date_ceated',models.DateField(auto_now_add=True)),
        ],
    ),
]